# Generated by Django 5.0.4 on 2024-05-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gostos',
            field=models.IntegerField(default=0),
        ),
    ]
