# Generated by Django 5.0.4 on 2024-05-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_condutor_id_alter_condutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, default='lesunshine.jpg', upload_to=''),
        ),
    ]
