# Generated by Django 5.0.4 on 2024-05-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
