# Generated by Django 5.0.4 on 2024-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='condutor',
            name='avatar',
            field=models.ImageField(blank=True, default='forum/images/default.png', upload_to=''),
        ),
    ]
