# Generated by Django 5.0.4 on 2024-05-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_condutor_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcomentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcomentario_texto', models.CharField(max_length=200)),
                ('gostos', models.IntegerField(default=0)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.comentario')),
            ],
        ),
    ]
